/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_catch22_chainsaw_CatchLib */

#ifndef _Included_com_catch22_chainsaw_CatchLib
#define _Included_com_catch22_chainsaw_CatchLib
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_catch22_chainsaw_GLRenderer
 * Method:    nRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_catch22_chainsaw_GLRenderer_nUpdate
  (JNIEnv *, jclass, jfloat dt);

/*
 * Class:     com_catch22_chainsaw_GLRenderer
 * Method:    nInit
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_com_catch22_chainsaw_GLRenderer_nInit
  (JNIEnv *, jclass, jint, jint, jintArray);


/*
 * Class:     com_catch22_chainsaw_GLRenderer
 * Method:    nPassInputEvent
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_catch22_chainsaw_GameView_nPassInputEvent(JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_catch22_chainsaw_GameActivity
 * Method:    updateDeviceOrientation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_catch22_chainsaw_GameActivity_updateDeviceOrientation(JNIEnv* enc, jclass clazz, jint deviceOrientation);

#ifdef __cplusplus
}
#endif
#endif
